const Products = [
    {
        id: 1,
        categoryId: 2,
        title: "Latte chocolate",
        weight: "50gr",
        price:"90",
        picture:"https://caramelandia.com/wp-content/uploads/2022/02/WhatsApp-Image-2022-03-23-at-1.20.05-PM-3.jpeg",
        description: "Chocolate Latte con mani en version de 50gr en cajita con frase.",
        dimension: "8 × 3 × 4 cm",
    },
    {
        id: 2,
        categoryId: 6,
        title: "Pochoclo Dulce Funny Pop",
        weight: "100gr",
        price:"300",
        picture:"https://caramelandia.com/wp-content/uploads/2022/02/WhatsApp-Image-2022-03-23-at-1.20.08-PM.jpeg",
        description: "Pochoclos en bolsa de diferentes sabores",
        dimension: "7 × 24 × 13 cm",
    },
    {
        id: 3,
        categoryId: 2,
        title: "Tableta Latte Chocolate",
        weight: "80gr",
        price:"380",
        picture:"https://caramelandia.com/wp-content/uploads/2022/02/AIL_6451-600x401.jpg",
        description: "Chocolate Con Leche Y Mani, Con Frase. Sin Taac",
        dimension: "2 × 8 × 16 cm",
    },
    {
        id: 4,
        categoryId: 4,
        title: "Paleta Corazon De Caramelo",
        weight: "50gr",
        price:"140",
        picture:"https://caramelandia.com/wp-content/uploads/2022/02/WhatsApp-Image-2022-03-28-at-4.39.59-PM-3.jpeg",
        description: "Paleta Corazon De Caramelo Artesanal",
        dimension: "1 × 8 × 21 cm",
    },
    {
        id: 5,
        categoryId: 4,
        title: "Paleta Redonda De Caramelo",
        weight: "40gr",
        price:"120",
        picture:"https://caramelandia.com/wp-content/uploads/2022/02/AIL_6564.jpg",
        description: "Paleta Redonda De Caramelo Artesanal",
        dimension: "1 × 7 × 21 cm",
    },
    {
        id: 6,
        categoryId: 2,
        title: "Chocolate Blockazo",
        weight: "1kg",
        price:"2600",
        picture:"https://caramelandia.com/wp-content/uploads/2022/05/WhatsApp-Image-2022-05-12-at-5.39.44-PM-600x800.jpeg",
        description: "Chocolate Cofler Block de 1kg. Blockazo.",
        dimension: "17 × 4 × 20 cm",
    },

]

export default Products;